### ISSUE TITLE
Automatic creation of reverse SSH tunnels

### ISSUE THREAD

**Issue by romain-jacob** [nsg-ethz/autopower#19]
It would be useful to have a reverse SSH tunnel automatically created from the client to the server (e.g., at the end of the client registration process). 

This will allow SSHing into a client even if that client is behind a NAT.

**Comment by UsualSpec** [comment]
Basically done now. The https://github.com/nsg-ethz/autopower/blob/main/client/signCerts.sh script may need some more adaptations to automate the setup for the server side.

**Comment by UsualSpec** [comment]
--> Use another server for this.

**Comment by UsualSpec** [comment]
Outstanding: Test on real device,
automating copying of the client key.

**Comment by UsualSpec** [comment]
Ok. Tested and fixed a bug with autopower{n} devices where n < 10.
