### ISSUE TITLE
Get client side available MCP counters/interfaces to ensure that only valid interfaces can be selected

### ISSUE THREAD

**Issue by UsualSpec** [nsg-ethz/autopower#2]
Currently, the clients have a whitelist for which counters are allowed: https://github.com/nsg-ethz/autopower/blob/8c40c9d66958f3a008e80ac1d7589f2eb8fe1859/client/config/client_config.json.example#L8 this is to prevent wrong inputs and unavailable interfaces on the client side. 
It would be good if:
* The server could receive available counters e.g. via a new gRPC message
* Restrict the user input already on the available counters
* In future, we could call pinpoint -l directly and parse the available counters

**Comment by romain-jacob** [comment]
Right now we see MCP2 listed in the webUI, but we can't start measurements from it. I suppose that's because of that whitelisting? Sometimes we do want to test on MCP2 (and not MCP1)

It should be easy to solve, so marking it as Priority.

I'm not sure what would happen in the database if we were to select more than one target though. We should discuss this.

**Comment by UsualSpec** [comment]
--> edit the client_config.json files on the devices in question to also include MCP2.

We can just edit the example config... Is that enough? I do not have access to the current deployment anyway.

Changing to > 1 target would require a larger rewrite of both the client and server, but mostly the client. Not impossible, but the question is if it's actually needed.

**Comment by romain-jacob** [comment]
It would be nice but that's definitely not a must. Being able to select any one channel will do for now.

**Comment by UsualSpec** [comment]
A slightly more involved but flexible version is now in #34 - still to be tested. I'd like to restrict the UI selector in the Web UI and CLI too - to only allow specific counters.
Potentially, the whitelist is still good to have: If the device has too many counters. But that's quite unlikely IMO.

**Comment by UsualSpec** [comment]
Completed. Still to be tested with a real measurement device, but it works locally.
