### ISSUE TITLE
[DOC] Control over the webUI only works within the ETH network

### ISSUE THREAD

**Issue by romain-jacob** [nsg-ethz/autopower#27]
... at least it seems to be the case, though I don't know whether it's intentional. Might want to rethink this, and at least document it (if it's not already somewhere...)

**Comment by UsualSpec** [comment]
No. This should definitely not be the case.

**Comment by UsualSpec** [comment]
Closing as can't reproduce. Please reopen this issue if it still occurs.

**Comment by UsualSpec** [comment]
Maybe re-signing certificates externally didn't work? I've changed the signCerts.sh script now to use the jump host.
