### ISSUE TITLE
[Bug?] Retrieving data from clients that fail to register

### ISSUE THREAD

**Issue by romain-jacob** [nsg-ethz/autopower#28]
I have a couple of clients that fail to register to the server (they are running older binaries). Their local database does contain valuable data though. 

What would be the recommended way to extract that data and push it manually to the server's database?

**Comment by UsualSpec** [comment]
While it is possible to issue a manual data upload, I‘d rather update the binaries. There shouldn’t have been any DB changes and the new binary should upload without error.

**Comment by romain-jacob** [comment]
So just replace the binaries on the SD card and restart the mmclient service?

**Comment by romain-jacob** [comment]
well, I'll have to reboot anyway, so restarting ain't needed I guess

**Comment by romain-jacob** [comment]
It was in fact a certificate issue. But now I have the client registering but its not uploading its data. Ive tried restarting mmclient on the client side, but that didn't do the trick. Any suggestion?

**Comment by romain-jacob** [comment]
Never mind, it seems it started now... just took a little while
