### ISSUE TITLE
Fix the certificate target

### ISSUE THREAD

**Issue by romain-jacob** [nsg-ethz/autopower#30]
Currently, the certificate still points to the VM hostname (ee-tik-nsgvm057.ethz.ch) but should be updated to use the new domain name (autopower.ethz.ch)

Also relate somewhat to #14

**Comment by UsualSpec** [comment]
I'm currently waiting on the update from SWITCH to update the new url in their registry. If this works, it should be done.

**Comment by UsualSpec** [comment]
Done.
